### ISSUE TITLE
Emails are not sent, even test email is not sent.

### ISSUE THREAD

**Issue by sajalaspl** [mageplaza/magento-2-smtp#115]
Magento 2.2.4

When I access, MagePlaza SMTP configuration page on admin side, I get following JS error.

https://magento.examplesite/static/adminhtml/Magento/backend/en_US/mageplaza/testemail.js ==> NOT FOUND

I tried following commands with no luck:
php bin/magento setup:static-content:deploy
php bin/magento setup:upgrade

Although, I've found that there's testemail.js in the following location:

pub/static/adminhtml/Magento/backend/en_US/Mageplaza_Smtp/js

Then why, it's trying to access from different location i.e. "static/adminhtml/Magento/backend/en_US/mageplaza/".

Any help appreciated.

**Comment by datvm231** [comment]
Hi,

The path to file testemail.js is changed to `mageplaza/testemail` by [requirejs](https://github.com/mageplaza/magento-2-smtp/blob/master/view/adminhtml/requirejs-config.js)

It should apply after deployed. Could you try clearing your magento_root_directory/pub/static folder and run deploy command again?

Otherwise, you can change it to the real path where it is called, [here](https://github.com/mageplaza/magento-2-smtp/blob/master/view/adminhtml/templates/system/config/button.phtml)
edit `mageplaza/testemail` to `Mageplaza_Smtp/js/testemail`

**Comment by datvm231** [comment]
We will close this issue due no response within 7 days. If your problem persists, please let us know further detailed report.
