### ISSUE TITLE
Empty requirements in composer.json

### ISSUE THREAD

**Issue by jissereitsma** [mageplaza/magento-2-smtp#148]
Hi, your module is used by a client of mine and this client reported that your module did not work under PHP 7.2. I took a look at your code now and was surprised to see that there is no indication for the PHP version in your `composer.json` version. Because of this, one of the most vital reasons for using composer falls away: Checking upon requirements before actually installing things. Furthermore, the `composer.json` does not reflect upon any of the other requirements it has (the framework, `Magento_Store`, `Magento_Ui`). Could you add this to your `composer.json` file? FYI, I have developed a tool to help with this (https://github.com/yireo/Yireo_ExtensionChecker) but it should really be picked up by the developer who built the original module.

**Comment by Arthas78** [comment]
Hello, I have met a few cases as your customers describe(https://prnt.sc/m2j5hi). In my opinion, the problem doesn't come from the SMTP module. This comes from the fact that dn_to_utf8 does not accept empty strings (strings of length equal to 0) and issues a warning when $ email is an empty string. Since this is a problem in the magento core, the best solution is to downgrade the php version. You can refer to the following 2 links for more details
https://github.com/zendframework/zend-validator/issues/93 || http://prntscr.com/n1uqsy
https://github.com/roundcube/roundcubemail/issues/6075
In addition, thank you very much for the feedback of the module, I will note it and inform the manager to ask for more comments on this issue. Thank you again!

**Comment by jissereitsma** [comment]
Thanks for the quick update. Interesting point. So the issue seems to have been fixed by the Zend Validator team already (https://github.com/zendframework/zend-validator/commit/6121d4f0af0272fd4f8621e779e8b120d232a80c#diff-59ac00efccae162aaeeaceaeec0a8088 - if I'm interpreting this correctly) so theoretically, this could be fixed if you would add a requirement for Zend Validator 2.12.0 (the core ships with 2.11.1). I've tested this out (`composer require zendframework/zend-validator:2.12`) but this fails. I completely understand the advice to use a lower PHP version instead. But then it would be best to simply add that lower PHP version as a requirement of this module. Composer to the power!

**Comment by Arthas78** [comment]
I checked the code, it was strange that they intentionally let idn_to_ascii use INTL_IDNA_VARIANT_2003. idn_to_ascii function deprecated the INTL_IDNA_VARIANT_2003 variant in PHP 7.2. 
However, I also feel that using composer to validate PHP version is a feasible way. I have noted your feedback to my manager. Thank you again!

**Comment by Arthas78** [comment]
dot-mailler can send with all mail in Magento. Though email is configured from external modules

**Comment by Arthas78** [comment]
I close the issue here.
Thank you very much!

**Comment by jissereitsma** [comment]
Np, thanks!
