### ISSUE TITLE
Handling of commata in sender name for resend action

### ISSUE THREAD

**Issue by simonrl** [mageplaza/magento-2-smtp#154]
Hi,

I noticed a small problem when the sender name contains a comma.

Using the latest version (1.2.9) on Magento 2.1.14.

**Configuration**:
_Sender-Address_: info@company.com
_Sender-Name_: Company, Inc.

When an email is sent, the sender gets saved in the database like this:
_"Company, Inc." <info@company.com>_

I then try to resend the email from the interface in the admin backend and get an error.

Tracing the code:

In `Model/Log.php::resendEmail()`, we have:
`$sender = $this->extractEmailInfo($data['sender']);`

Where the first line of `extractEmailInfo()` is:
`$emails = explode(', ', $emailList);`

This gives the following error message in my system.log file:
_main.CRITICAL: <Company>: "@" or "." expected after "Company"_

Not a huge issue, but fix would be nice.

TY!

**Comment by Arthas78** [comment]
I tried testing your problem on my site. I found it was sent but the way it shows up in my inbox is incorrect( http://prntscr.com/n7rn39). I add the code(http://prntscr.com/n7rwwo) and saw it work (http://prntscr.com/n7rxn4). I am currently trying to fix all the problems that appear on the new Magento so if you have any problems, please inform me so I can note and fix it in the new version SMTP. One final note, I found the email name field should only contain the name, you should not write any more characters behind because it will break the structure.

**Comment by simonrl** [comment]
Hi,

thanks for your fast response.

@"Email gets send": the email also gets send initially for me, I only experience the problem when using the resend-functionality.

@"I found the email name field should only contain the name, you should not write any more characters behind because it will break the structure.": yes, only the ", Inc." is part of the company's name: "Company, Inc."

We have resolved the problem by simply removing the "," from the name (now: "Company Inc."), as this is what breaks the code as I outlined above.

So, no problem if this gets fixed later or if this is a "wontfix" issue. Can be closed if you like,

--Simon

**Comment by Arthas78** [comment]
I close the issue here.
Thank you very much!
