### ISSUE TITLE
Could not open socket

### ISSUE THREAD

**Issue by jgutierrezs** [mageplaza/magento-2-smtp#16]
I have this error with gmail account. I use Magento 2.2

**Comment by gixid192** [comment]
To be honest, we haven't received any reports about this issue.
Please help us once again check your settings follow these 2 links:
 
https://support.google.com/a/answer/176600?hl=en
https://support.google.com/accounts/answer/6010255?hl=en
 
Thank you.

**Comment by LouNik1984** [comment]
I have this error too, on Magento 2.1.9... I've installed the plugin just now, installed through composer and no error during installation. Setting parameters seemed to go smoothly but when I tried to test the connection (to elastic mail) I got the same error : could not open socket

**Comment by michelve** [comment]
same issue for me on 2.2.3

**Comment by koopjesboom** [comment]
Magento 2.2.4 I got the same error : could not open socket If I switch to SSL and I have the ssl certificate on I get this error.

**Comment by CatDTran** [comment]
I got the same error. Also turn on the Less Secure App setting through goolgle but it doesn't seem to help!

**Comment by gixid192** [comment]
Guys, kindly check again your server settings first, see if your mail server is configurated correctly.
If you are using 2.2.2 and above, use Dotmailer Transaction Email which is shipped with Magento by default to verify your connection: https://www.screencast.com/t/wSLA3bZsAZkZ

There is another tool to test the connection which is PhpMailer https://github.com/PHPMailer/PHPMailer
If everything is working with another tool, kindly report here, we will check the problem with our Smtp tools.

**Comment by koopjesboom** [comment]
Best,

The issue is not that this is a once of a lifetime event, the log files are filling with these messages.
And no i am not pressing the "Send Test Email" button all day.

Server and backend information.

Apache-version 		2.4.29
PHP-version 			5.6.34
MySQL-version 		5.6.39-cll-lve
Architecture 			x86_64
Operating system 		Linux
Magento version 		2.2.5
Magento Folder		Public_html
PHP-version			7.1
Magento Theme		Porto
Porto Theme version	        3.1.3

Best regards

**Comment by gixid192** [comment]
These 2 things, I think you guys are misunderstanding.
- Dotmailer is a tool for testing purpose.
- The server information doesn't matter

First, Dotmailer is a tool, just like our tool, don't use both. Use Dotmailer to verify your mail function.

Not sure why you gave the server information, as long as you can run Magento, it's fine.
The thing to check on the server is the mail function, check if the port to the mail server is blocked or even opening.

My advice is to use another tool to verify all of the information above, Dotmailer is fine, Phpmailer is popular in the field.
If one tool works and the others don't, then the others have problems, if all tools don't work, all tool are wrong or the thing that used in the tool is not function.

**Comment by CatDTran** [comment]
So I contacted my hosting provider, it turns out that the reason for "Could not open socket" error is because I'm using a shared hosting account. My hosting provider does not allow external SMTP for shared hosting account due to security concern. If you guys are encountering this problem, I recommend checking with your hosting provider to see if they allow SMTP module to open the needed socket.

I also tried other SMTP modules to make sure that this error is not from this module, I can confirm that other SMTP module also throws "Could not open socket" error. That leads to the conclusion that, the error is NOT from this SMTP module.

Hope this info will help those who are having a similar issue. Cheer!
