### ISSUE TITLE
sending issues after upgrade to 2.3.1, Transaction failed: Domain contains illegal character

### ISSUE THREAD

**Issue by dni** [mageplaza/magento-2-smtp#164]
Hi i upgraded to magento 2.3.1 and now im getting this error: Transaction failed: Domain contains illegal character on every mail i try to send, even the send testmail failed.

i got this error before on my Subject becaues i had a ü character in it i removed it and then it worked, now with the domain this isnt as simple, and i got no special chars in there.
any help would be appreciated!

**Comment by Arthas78** [comment]
I'm afraid the problem is in your configuration information. Please disable the SMTP module and configure it in dot-mailler of magento. Then go out to the frontend to check, if your email is still not sent, I believe your problem doesn't come from the SMTP module, check with the host or server. You can refer the link
https://groups.google.com/forum/#!topic/openesignformsdev/av9CHYdXaYE
https://developer.salesforce.com/forums/?id=906F00000008ybXIAQ

**Comment by dni** [comment]
i don't really think its a host thing, because it was working before the upgrade, disabling smtp module now though gives me an unknown error :(, damn any idea where to look? downgrading php from 7.2 to 7.1 doesnt help either

**Comment by Arthas78** [comment]
Sorry for the late reply. You can try the code(if you are using SMTP version 1.2.10) || http://prntscr.com/nma63k
In addition, I cannot confirm that this is a problem derived from the SMTP module. You should disable the SMTP module and try it on dot-mailler (this is a Magento tool created to check the SMTP configuration information)

**Comment by dni** [comment]
ok found the issue, 
the encoding of the return-path is wrong, leaving it blank in the smtp settings fixes the issue...

action: vendor/zendframework/zend-mail/src/Transport/Smtp.php. Set a breakpoint at line 258 and check out the headers in the $message

headers:
Return-Path: =?utf-8?Q?info@metalldetektor-austria.at?=

**Comment by Arthas78** [comment]
I am very happy that you have tried to solve the problem. Actually, I have set the encoding to 'utf8' before || (http://prntscr.com/npqf90 ). I will check this on my site.
Thank you for your information

**Comment by pieterpoorthuis** [comment]
On our M2.3.1 store, Magento 2 smtp v1.2.9 works successfully but 1.2.10 breaks. Error message is as above ("Domain contains illegal character")

I fixed the issue by downgrading to 1.2.9...

**Comment by jpelayo** [comment]
I used the development branch with my Magento 2.3.2 php 7.2 .
This issue seems still happening for Amazon SES email-smtp.eu-west-1.amazonaws.com :

[2019-08-13 13:16:12] main.CRITICAL: Transaction failed: Domain contains illegal character
{"exception":"[object] (Magento\Framework\Exception\MailException(code: 0): Transaction failed: Domain contains illegal character
at /var/www/html/app/code/Mageplaza/Smtp/Mail/Transport.php:132, Zend\Mail\Protocol\Exception\RuntimeException(code: 0): Transaction failed: Domain contains illegal character
at /var/www/html/vendor/zendframework/zend-mail/src/Protocol/AbstractProtocol.php:348)"} []
