### ISSUE TITLE
Test-email is sended. All other shows Error in mail-log

### ISSUE THREAD

**Issue by JustMe69** [mageplaza/magento-2-smtp#167]
Hi,
I'm using Magento, V 2.2.1
SMTP plugin is installed via composer. we are also using other mageplaza plugin which wokrs, so core module is installed and working.
from the require part in composer.json:
`        "mageplaza/magento-2-blog-extension": "^2.6",
        "mageplaza/module-delete-orders": "^1.1",
        "mageplaza/module-smtp": "^1.2"
`
As smtp server a custom server is configured. TLS is at port 587 used.
The Test-Email (one is recieved) is sended immideatly. When ordering i.e., no email is sent. Not to the customer, nor the copy.
In the email-Log I can only see the not sended mail with status error. 

* How can I see what error occurred?
* What am I'm doing wrong that emails are not sended?
* I configured return-path email - there's no income.

Thanks for help

**Comment by Arthas78** [comment]
If you have successfully sent the email test, I believe the SMTP module is working. You should check with other types of mail like the subscribe forgot email to see if they can be sent. Also, as you describe the status of all order emails as 'error', you can check in var/log/exception.log to identify the error. Finally, you can check with dot-mailler (this is a tool of Magento created that functions similar to the SMTP module)(http://prntscr.com/no74h9). Please disable the SMTP module and configure on dot-mailler, then go out to the front end to check if your email order is still not sent, I'm afraid your problem is not coming from the SMTP module, please check to see if any 3rd party modules interfere with the default order email flow

**Comment by JustMe69** [comment]
I Tried to use dotmailer - All emails are still sended via localhost?
Very strange. o I have to change in default config something? Any hints where to look?

**Comment by Arthas78** [comment]
As mentioned above dot-mailler has the same function as the SMTP module (you must disable the SMTP module before trying dot-mailler). Have you tried sending your email order via dot-mailler? If your email order is still not sent, I think you should check in var / exception.log to identify the problem why the message was not sent

**Comment by Arthas78** [comment]
Do not receive any feedback in the last 7 days, I will close the issue here.
Have a nice day!

**Comment by JustMe69** [comment]
Error was, that an other extension was used to send the mails. SMTP-Hoster told, that mails were using wrong header information. emails were rejected immedeatly by smtp-server without sending info.
After fixing this issue, mails are sended via SMTP-Plugin.
Closing issue is completly correct.
