### ISSUE TITLE
SMTP Test Email not working

### ISSUE THREAD

**Issue by farhangithub27** [mageplaza/magento-2-smtp#168]
Magento 2.3.1
mageplaza smtp 1.2.10
Magento is running in developer mode but setting for smtp developer is set to 'no'.

I'm getting following error when I run test email

main.CRITICAL: Zend\Mail\Protocol\SmtpPluginManager::get was unable to fetch or create an instance for  {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Zend\\Mail\\Protocol\\SmtpPluginManager::get was unable to fetch or create an instance for  at /var/www/html/magento23demo/vendor/mageplaza/module-smtp/Mail/Transport.php:132, Zend\\ServiceManager\\Exception\\ServiceNotFoundException(code: 0): Zend\\Mail\\Protocol\\SmtpPluginManager::get was unable to fetch or create an instance for  at /var/www/html/magento23demo/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:555)"}

**Comment by Arthas78** [comment]
Please check your SMTP configuration information( especially Authentication field). You can change Authentication field value to "Login", flush the cache and check your site again.

**Comment by farhangithub27** [comment]
@Arthas78 Login doesn't work with my smtp server it says 5.7.4 unrecognized authentication type.
with Authentication 'None' it gives subject mentioned error. FYI MagePal extension is working fine.

**Comment by Arthas78** [comment]
This is the problem with your SMTP configuration information. Try contacting the hosting provider so they can check for you. In addition, you can turn off the SMTP module and use dot-mailler (this is a Magento tool created to check the SMTP configuration information)(http://prntscr.com/nr8758) to check your configuration information.
If dot-mailler is also unable to support your SMTP server, I am afraid that the SMTP module is also not possible (because the SMTP module will use the same mail flow as dot-mailler). You can try again with another SMTP server

**Comment by farhangithub27** [comment]
@Arthas78 MagePal extension is working with my SMTP server and I'm using same settings for your extension but it doesnt work. I have made the settings as per picture you shared but still it didn't work.

**Comment by Arthas78** [comment]
As mentioned above, you should only use 1 SMTP module because if you use more they will override each other's streams which will cause you to be unable to send an email. If you have tried using dot-mailler but the problem still occurs, I think your mail flow now runs under the main flow of the MagePal extension. As you said, if you are using the SMTP module well on the MagePal extension side, you should disable our SMTP side to avoid compatibility issues.

**Comment by Arthas78** [comment]
7 days have passed without any feedback from you, I will close the issue here.
Thank you very much!
