### ISSUE TITLE
Authentification "NONE" does not work

### ISSUE THREAD

**Issue by m-schreiber** [mageplaza/magento-2-smtp#183]
When Authentication is set to "none" the actual value is an empty string, which is used as a ConnectionClass-Identifier in the Zend-Mail-SMTP-Options which leads to an exception.

Please fix !

The easiest way would be to change this
https://github.com/mageplaza/magento-2-smtp/blob/3e0707fdbcfdaa5b0dbb016c603fa30101041b3d/Model/Config/Source/Authentication.php#L41
to
`''value' => 'smtp',`

**Comment by Arthas7895** [comment]
First, thank you for the findings for our module.
Second, we checked and found how to correct the code in magento-2-smtp / Model / Config / Source / Authentication.php not exactly because it will affect the flow of Magento versions below 2.2.8
We found the solution and will update in the new version
Thank you very much!

**Comment by Arthas7895** [comment]
Because there are solutions at your PR, I'm going to close this issue, if there are any problems, please contact me. 
Thank you very much!

**Comment by alinalexandru** [comment]
@Arthas7895 What is the fix for this issue?
