### ISSUE TITLE
Transaction failed: Domain contains illegal character (Transport.php )

### ISSUE THREAD

**Issue by jpelayo** [mageplaza/magento-2-smtp#191]
I used the development branch with  Magento 2.3.2 php 7.2 .
Mageplaza Core installed with Composer. Plugin works fine with a regular smtp server, not with SES.

_Originally posted by @jpelayo in https://github.com/mageplaza/magento-2-smtp/issues/164#issuecomment-521108085_

This issue seems still happening for Amazon SES email-smtp.eu-west-1.amazonaws.com :

[2019-08-13 13:16:12] main.CRITICAL: Transaction failed: Domain contains illegal character
{"exception":"[object] (Magento\Framework\Exception\MailException(code: 0): Transaction failed: Domain contains illegal character
at /var/www/html/app/code/Mageplaza/Smtp/Mail/Transport.php:132, Zend\Mail\Protocol\Exception\RuntimeException(code: 0): Transaction failed: Domain contains illegal character
at /var/www/html/vendor/zendframework/zend-mail/src/Protocol/AbstractProtocol.php:348)"} []

**Comment by jpelayo** [comment]
I have pinpointed the issue:

Setting the Return Path manually  (option Return-Path Email in Mageplaza configuration section) forces transport.php in $message headers as

debug.log entry:
main.DEBUG: Return-Path: =?utf-8?Q?testmail@example.com?= [] []

Which is disliked by Amazon SES.

**Comment by Desmond-Mageplaza** [comment]
Hi @jpelayo,
Sorry for the late response

So great to hear that you are able to pinpoint and fix the issue.
Again, with Amazon SES, I recommend not setting return path email since the service is really sensitive with character encoding and domain verification.
Also, please make sure that you have the correct SMTP credentials for SMTP configuration.
Not the access and secret keys which are used for sending mail from SDK or console.

As the issue has been resolved, I will close this issue
Thank you
