### ISSUE TITLE
Error sending email

### ISSUE THREAD

**Issue by daviddela12** [mageplaza/magento-2-smtp#197]
I have configured it with Protocol TLS. Magento version 2.3.1.
Error sending test email:

> Warning: stream_socket_enable_crypto(): Peer certificate CN=`... did not match expected CN=`...' in vendor/zendframework/zend-mail/src/Protocol/Smtp.php on line 215

I changed, like I did successfully in a old version of Magento:
```
//$this->_socket = @stream_socket_client($remote, $errorNum, $errorStr, self::TIMEOUT_CONNECTION);
 $stream_context = stream_context_create(array(
            'ssl' => array(
                'verify_peer'       => false,
                'verify_peer_name'  => false,
                'allow_self_signed' => true
            )
        ));
```
However that didn't work at that new version of Magento.

Any idea about what is happening here?
Thanks, I hope your answers

**Comment by Arthas7895** [comment]
Magento versions 2.3 and above use Zend 2 to configure transport for sending mail. It is completely different from Zend 1. You can try the following code
`stream_context_set_default([
"ssl"=>[
"verify_peer"=>false,
"verify_peer_name"=>false,
]
]);`
If it still doesn't work, the best way you should contact your web server to check the SSL issue because the above method is to disable SSL on your site, it does not completely solve the problem thoroughly.

**Comment by daviddela12** [comment]
It has solved the problem. Anyway, I will contact with web server staff to check that...I understand its cause of the smtp host doesn't match with the dns server

**Comment by Arthas7895** [comment]
Great! It's a pleasure to hear the code works for you, I will close the issue here
Have a nice day!

**Comment by ebofi** [comment]
@Arthas7895 

We still have this issue,.

Warning: stream_socket_enable_crypto(): Peer certificate CN=`sub.site.cloud' did not match expected CN=`in-v3.mailjet.com' in /home/backup/public_html/vendor/zendframework/zend-mail/src/Protocol/Smtp.php on line 215

**Comment by nmarquev** [comment]
same issue here
