### ISSUE TITLE
Test Emails Working & Order Emails Working but not newsletter emails

### ISSUE THREAD

**Issue by manibibek** [mageplaza/magento-2-smtp#238]
Reference issue https://github.com/mageplaza/magento-2-smtp/issues/200

Hi, 

I am currently facing the same issue as above. The email is perfectly working for all modules such as test email, sales, email verification, invoice, etc. It is only not working for the newsletter. 

I checked the email log and I found that the status is **ERROR**. I tried resending it from the same log page and it returned the error **We can't process your request right now.**. 

I debugged further to system.log, the issue was **Sender syntax error**. It was strange so I went to the Email log again and I found that for all the success emails the `Sender` format was `Sender Name <example@email.com>` and my failed newsletter format was `example@email.com <Sender Name>`. 

So I tried to switch the sender name and email from the `Newsletter Queue` edit page but couldn't do it due to validation for the specific email field. 
So I switched the name and email part from the database and put it again in the queue. I put the sender name as `example@email.com` and put the email to `Sender Name` And yes, all the emails were sent successfully. It was only a quick workaround for testing and finding the issue. Can you please fix the issue from your end. 

I am currently using Magento Version 2.1.7 and sendgrid for smtp

**Comment by Arthas7895** [comment]
The SMTP module only has the task of connecting to the mail server that you have configured and sent message information through. 
If the email on your site has been sent, the module is working normally (the problem is not on the module). 
As for the email newsletter issue as you described, I think there's a third module that interferes with the mail flow of your newsletter form. Try disabling the 3rd modules that you have installed on your site and try again on the site. This takes a lot of time, but this is the only way to know which module your problem is coming from

**Comment by Arthas7895** [comment]
It's been 7 days without a response from you so I'll close this issue here
Have a nice day!
