### ISSUE TITLE
Magento 2 SMTP emails Test email is working but other emails are not working

### ISSUE THREAD

**Issue by darshantechspacio** [mageplaza/magento-2-smtp#246]
Hello,

I am using Magento 2.2.6 and I have enable mageplaza SMTP and I have set all the credentials properly now Test email is working but other emails like registration, forgot password, order placed are not working. Can anyone please help me with this ?

**Comment by Arthas7895** [comment]
If your test email has been sent and the emails outside the front end have not been sent, you should check with the mail server because that is where the recipient's mail is sent. 
First, you need to check the mail log in the admin and see the status of the mail. If they say success, you need to check with your mail server. If it is an error, you need to go to var/log to check for an error. If there is no record that the site you are using does not run through the SMTP module, you need to check the 3rd module you have installed.

**Comment by Arthas7895** [comment]
It's been 7 days since I received your response, so I will close this issue here
Thank you!

**Comment by mattqiu** [comment]
> It's been 7 days since I received your response, so I will close this issue here
> Thank you!

Hi,do you know to solve this problem? https://github.com/mageplaza/magento-2-smtp/issues/277
