### ISSUE TITLE
Could not open socket: stream_socket_client 

### ISSUE THREAD

**Issue by robertbaum** [mageplaza/magento-2-smtp#250]
Hi,
Sometimes the email wasn't sending, for example, 1 of 5 not send

and I am getting this error at the debug.log

Could not open socket: stream_socket_client(): unable to connect to tcp://smtp.sendgrid.net:587 (Connection timed out) 
could you please help me to fix it 

Nginx
Magento 2.3.3
mageplaza SMTP

Host: smtp.sendgrid.net
Port:  587
Protocol: TLS
Authentication: Login

**Comment by HuyPhuc98** [comment]
It turns out that the reason for the "Could not open socket" error is because You're using a shared hosting account. Your hosting provider does not allow external SMTP for shared hosting account due to security concern.

If you guys are encountering this problem, I recommend checking with your hosting provider to see if they allow SMTP module to open the needed socket.

Hope this info will help those who are having a similar issue. Cheer!

**Comment by robertbaum** [comment]
thanks,
but I am not using shared hosting and the email is sending most of the time,
I used a Gmail SMTP without any issue

I just facing this with this SMTP
Host: smtp.sendgrid.net
Port:  587
Protocol: TLS
Authentication: Login****

**Comment by HuyPhuc98** [comment]
If your Gmail SMTP config runs normally but your SendGrid SMTP config is an error, you need to contact with SendGrid side so they can check your connection information or port which you are using so connect. You can try to use telnet(use your SendGrid SMTP information) on your server so check to connect with your mail server.

**Comment by robertbaum** [comment]
ok,
many thanks
I will check with SendGrid
