### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large

### ISSUE THREAD

**Issue by fajriarma** [mageplaza/magento-2-smtp#267]
Hi all, I run bin/magento setup:upgrade, showing : SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
any solution?

**Comment by fajriarma** [comment]
Installing schema... Upgrading schema... SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

**Comment by HuyPhuc98** [comment]
Hi,

Your problem is due to a MySQL/InnoDB server limitation.
Please try adding "innodb_strict_mode = 0" to my.cnf

If problems still exist please get more information and solution via this thread:
https://craftcms.stackexchange.com/questions/11480/internal-server-error-sqlstate42000-1118-row-size-too-large?fbclid=IwAR3CLM98Crh0mG19Rc_MQQEGwMrw3h9aw9GCzaSqy52XNxvY7PiIRRBx-og

Thank you!

**Comment by fajriarma** [comment]
yes already add.. thank you so much

**Comment by HuyPhuc98** [comment]
Hi,

Since there are no more problems I will close this one for now.
Thank you!
