### ISSUE TITLE
254864

### ISSUE THREAD

**Issue by awglaat** [mageplaza/magento-2-smtp#268]
### Preconditions (*)

1. php 7.4
2. magento 2.4
3. mageplaza smtp 1.4.3

### Steps to reproduce (*)

1. install mageplaza smtp
2. configure smtp for outlook.com
3. send test message
4. check magento log in var/log/exception.log 

### Expected result (*)

1. email send to test email.
2.

### Actual result (*)

1. critical issue
2. no email send to test email

[2020-09-29 19:30:20] main.CRITICAL: 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [AM0PR10CA0081.EURPRD10.PROD.OUTLOOK.COM]
 {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [AM0PR10CA0081.EURPRD10.PROD.OUTLOOK.COM]
 at /home/sabe/domains/villasabe.com/public_html/vendor/mageplaza/module-smtp/Mail/Transport.php:142, Laminas\\Mail\\Protocol\\Exception\\RuntimeException(code: 0): 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [AM0PR10CA0081.EURPRD10.PROD.OUTLOOK.COM]
 at /home/sabe/domains/villasabe.com/public_html/vendor/laminas/laminas-mail/src/Protocol/AbstractProtocol.php:351)"} []

**Comment by HuyPhuc98** [comment]
Hi,

Your problem seems to be due to address authentication. The "from" needs to be a real address on the Office365 system.
On your issue, I think you should contact your mail server so that they can help you.

I also searched for some of the solutions for you.
https://stackoverflow.com/questions/30342884/5-7-57-smtp-client-was-not-authenticated-to-send-anonymous-mail-during-mail-fr/31289772#31289772  (http://prntscr.com/m3wmzg)

​Thank you!

**Comment by HuyPhuc98** [comment]
We will close this issue due to no response within 7 days. If your problem persists, please let us know further detailed reports.
