### ISSUE TITLE
Weird error after copying database

### ISSUE THREAD

**Issue by OvalMedia** [mageplaza/magento-2-smtp#325]
I have this weird error that keeps haunting me. Occasionally I copy a live database to my dev system.
Every time I do that mails will not be sent due to an authentication error.

`main.ERROR: 5.7.8 Error: authentication failed: UGFzc3dvcmQ6`

On the live site everything works fine. I think `UGFzc3dvcmQ6` used to be the smtp password but it has been changed a long time ago. I have no idea where the shop gets it from. I did a fulltext search in the database and on all the project's files but no success.

I have to reenter the current smtp data to make it work again.

Any clue where this info could be hidden? Cannot be the database, can it? I mean I completely dumped it.

**Comment by HuyPhuc98** [comment]
Hi,

The problem you have is caused by your incorrect password. 
You'll need to turn on two-step verification, then generate an app password via two-step verification for the account you're configuring using the following link:
https://support.google.com/accounts/answer/185833?hl=en

You can refer to the following screen recording video for how to create: https://www.screencast.com/t/ZGCQ5srGUcgk

Try it and let me know the results. 
Thank you!

**Comment by OvalMedia** [comment]
Sorry, but I think there is a major misunderstanding.
Google or 2fa has nothing to do with it. In fact 2fa is not even active/installed in this shop and also I am not using gmail. I am using my own e-mail server.

The solution is always to set the password for the mail account again. But why does the old password always reappear for some reason?

**Comment by HuyPhuc98** [comment]
Sorry for misunderstanding your issue.
As far as I see, this is due to your configuration issue, you need to contact your host provider so they can check this for you.
Thank you!

**Comment by OvalMedia** [comment]
nevermind...
