### ISSUE TITLE
Test mails are successfull, but no order mails are sending

### ISSUE THREAD

**Issue by shiyasVp** [mageplaza/magento-2-smtp#69]
Hi,
When i configure it with gmail smtp and test mail is sent, it is successful. But when order placed or anything, it is not sending any.

No errors also. Am using nginx server and Google Cloud Hosting
 also i cant even test using zoho smtp

**Comment by imsamthomas** [comment]
Hi,

Google Compute Engine does not allow outbound connections on ports 25, 465, and 587. By default, these outbound SMTP ports are blocked because of the large amount of abuse these ports are susceptible to. In addition, having a trusted third-party provider such as SendGrid, Mailgun, or Mailjet relieves Compute Engine and you from maintaining IP reputation with your receivers.

See https://cloud.google.com/compute/docs/tutorials/sending-mail/

You need a developer to configure email server on your Google Engine (VPS).

Regards,
Sam

**Comment by gixid192** [comment]
Close due to no response within 7 days.
