### ISSUE TITLE
Receiving multiple email

### ISSUE THREAD

**Issue by LAccorinti** [mageplaza/magento-2-smtp#81]
I configured the plugin and the email sending does work correctly.
The problem is that I recive multiple emails when a customer create and order: in the screenshot all the success emails are sent to the same recipient for the same order.
The emails is sent via cronjob.
![screenshot](https://user-images.githubusercontent.com/10450637/40708670-55eb17e2-63f4-11e8-9701-aebeb76eb07e.jpg)

**Comment by zebeel** [comment]
Please firstly disable our extension and check if you still receive multiple emails when the customer creates a new order. If the email sending works correctly when our extension is disabled, please go here: https://mageplaza.freshdesk.com/helpdesk and open a new ticket, our support is free. 
To speed up the support process, please provide us the following information: 
- Magento temporary login details (including Back-end URL)
- Temporary SSH/ SFTP log in details. (should be able to read/write pub/ var/ folders)

**Comment by pkd87** [comment]
I am also getting same issue. Emails is working but getting multiple email only for Sales order. And Sales order email is not working for multiple store. 
Sales email is working only when I have set value on default value.

**Comment by gixid192** [comment]
Close due to no response.

**Comment by selected-pixel-jameson** [comment]
I'm also seeing duplicate emails sent when creating a sales order. When I disable the Mageplaza module for SMTP then no emails are generated, but that is because we are using Mageplaza with Mailchimp / Mandrill to send emails out. So it seems obvious that it would not work if we disable this module. 

I'm not sure how to fix this? Any suggestions would be helpful. Running Magento 2.2.10.
