### ISSUE TITLE
Key must not exceed 32 bytes.

### ISSUE THREAD

**Issue by 911gt3rs** [mageplaza/magento-2-smtp#91]
Hi,
When I confirm the setting, I have this error. I tried with several email boxes and with short password but it does not change anything. (Magento 2.2.5)
![screenshot_2018-07-10 configuration settings stores magento admin](https://user-images.githubusercontent.com/33813714/42536257-cb2e354e-8491-11e8-9bec-637398b7ca09.png)

**Comment by gixid192** [comment]
This is not about our extension at all.
Magento 2.2.5 shipped Dotmailer Transactional Email by default, you can use it to verify.

The reason is in your app/etc/env.php file, you defined the `crypt-key` with more than 32 characters length.
![crypt-key](https://content.screencast.com/users/Lovemagic/folders/Jing/media/1f8e2766-bdbf-4d6c-8241-f536e525342c/2018-07-11_0915.png)

**Comment by 911gt3rs** [comment]
I just changed the key, it works well now. Thank you.
