### ISSUE TITLE
No link on admin menu

### ISSUE THREAD

**Issue by vindicopdl** [mageplaza/magento-2-smtp#92]
Afternoon team,

I've installed the extension by the numbers and it all looks like it went well, but the extension does not appear in the side admin menu.

Any ideas what to try or check?

**Comment by vindicopdl** [comment]
Actually it's worse than that.....

Now when I go to Admin/Store/configure I get this error

Notice: Undefined index: id in /var/www/html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63

Ripping out the plugin now.

**Comment by vindicopdl** [comment]
Sorted it.

**Comment by gixid192** [comment]
Great to know you resolved it.
We hope you can share your experience in this issue for everyone to know.

**Comment by mngoe** [comment]
Same problem here. Could you please explain how you solved ?

**Comment by vindicopdl** [comment]
I was installing by uploading by ftp but had the issues above, once I ripped it out I installed it via SSH and downloaded directly using

composer require mageplaza/module-smtp
php bin/magento setup:upgrade

Worked fine then

**Comment by gixid192** [comment]
Sounds like the issue comes from setting up steps to me.
@mngoe you can try what @vindicopdl suggested. Since this is a problem from setting up steps, I also suggest you to try with other extensions (any extensions from any vendors) to make sure that this only happens with our modules.
If you still have the problem, we will reopen this issue.
