### ISSUE TITLE
Test Button Configuration Uses Default Store Not Store Currently working in Config For

### ISSUE THREAD

**Issue by SnowCommerceBrand** [mageplaza/magento-2-smtp#93]
https://github.com/mageplaza/magento-2-smtp/blob/ce35004bfbc8d5a65b4b08ec53678f38ecad22d7/Controller/Adminhtml/Smtp/Test.php#L127

When testing configuring credentials at Store or Website Level The Test button still uses the Default Store credentials not the store working with for testing.

I think Should Be updated so that it pulls from \Magento\Store\Model\StoreResolver 

\Magento\Store\Model\StoreResolver $storeResolver
    {
        $this->store = $storeResolver;
    }
 $_storeId = $this->store->getCurrentStoreId();

I can Test this and create Pull request if necessary. 
Let me know.

Thank You,

**Comment by gixid192** [comment]
@SnowCommerceBrand Firstly, thanks for your report, really appreciate you spending your time writing to us.

Secondly, we did that on purpose, if the extension works well on Default store, it will work on all stores/websites, the reason is no code being changed between store/website, just the credentials.

The real code to send emails has the check for it, but for the Test, we make it simple enough to accomplish the `Test` purpose.

**Comment by SnowCommerceBrand** [comment]
Right I understand that but our client has different email accounts for
each website. These are domain specific so when testing a website it is
very confusing it looks like test will use the credentials at store or
website but in reality it uses default. This was very confusing for our
client they get dkim errors for store account at different domain because
it is trying to send as default store domain. The only way we could test if
credentials work for a store or website was to do a full order to get
emails triggered.

**Comment by gixid192** [comment]
@SnowCommerceBrand I see the issue now, kindly make a RP, I passed this information to the Core team, if they decide to have it, you will see it in the next release.
